-- MySQL Script generated by MySQL Workbench
-- Wed Oct  6 11:09:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema job_advertisements
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema job_advertisements
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `job_advertisements` DEFAULT CHARACTER SET utf8 ;
USE `job_advertisements` ;

-- -----------------------------------------------------
-- Table `job_advertisements`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_advertisements`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `description` VARCHAR(5000) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idcompanies_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job_advertisements`.`advertisements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_advertisements`.`advertisements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post` VARCHAR(250) NOT NULL,
  `description` VARCHAR(5000) NOT NULL,
  `address` VARCHAR(250) NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `companies_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_advertisements_companies1_idx` (`companies_id` ASC),
  CONSTRAINT `fk_advertisements_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `job_advertisements`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job_advertisements`.`peoples`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_advertisements`.`peoples` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `key_api` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idpeoples_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job_advertisements`.`candidats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_advertisements`.`candidats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idcandidats_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job_advertisements`.`candidats_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_advertisements`.`candidats_jobs` (
  `candidats_id` INT NOT NULL,
  `advertisements_id` INT NOT NULL,
  `motivation` VARCHAR(2500) NOT NULL,
  PRIMARY KEY (`candidats_id`, `advertisements_id`),
  INDEX `fk_candidats_has_advertisements_advertisements1_idx` (`advertisements_id` ASC),
  INDEX `fk_candidats_has_advertisements_candidats_idx` (`candidats_id` ASC),
  CONSTRAINT `fk_candidats_has_advertisements_candidats`
    FOREIGN KEY (`candidats_id`)
    REFERENCES `job_advertisements`.`candidats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidats_has_advertisements_advertisements1`
    FOREIGN KEY (`advertisements_id`)
    REFERENCES `job_advertisements`.`advertisements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job_advertisements`.`people_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_advertisements`.`people_jobs` (
  `advertisements_id` INT NOT NULL,
  `peoples_id` INT NOT NULL,
  `motivation` VARCHAR(2500) NOT NULL,
  PRIMARY KEY (`advertisements_id`, `peoples_id`),
  INDEX `fk_advertisements_has_peoples_peoples1_idx` (`peoples_id` ASC),
  INDEX `fk_advertisements_has_peoples_advertisements1_idx` (`advertisements_id` ASC),
  CONSTRAINT `fk_advertisements_has_peoples_advertisements1`
    FOREIGN KEY (`advertisements_id`)
    REFERENCES `job_advertisements`.`advertisements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_advertisements_has_peoples_peoples1`
    FOREIGN KEY (`peoples_id`)
    REFERENCES `job_advertisements`.`peoples` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
